body:
  - attributes:
      description: What version of Quests are you running? (Check Settings → General)
      label: Application Version
      placeholder: e.g., 1.1.1
    id: version
    type: input
    validations:
      required: true

  - attributes:
      description: What operating system are you using?
      label: Operating System
      options:
        - Select your operating system
        - macOS
        - Windows
        - Linux
        - Other
    id: operating-system
    type: dropdown
    validations:
      required: true

  - attributes:
      description: What type of processor does your computer have?
      label: Computer Processor Type
      options:
        - Select your processor type
        - Apple Silicon (M1, M2, M3, etc.)
        - Intel
        - ARM
        - Other
    id: cpu-architecture
    type: dropdown
    validations:
      required: true

  - attributes:
      description: How did you install Quests?
      label: Installation Method
      options:
        - Select installation method
        - Downloaded from website
        - Running in development mode
        - Other
    id: installation-method
    type: dropdown
    validations:
      required: true

  - attributes:
      description: Describe what you expected vs what actually happened
      label: Bug Description
      placeholder: |
        **Expected:** I expected X to happen when I...

        **Actual:** Instead, Y happened...
    id: bug-description
    type: textarea
    validations:
      required: true

  - attributes:
      description: Steps to reproduce the issue
      label: Steps to Reproduce
      placeholder: |
        1. Open the application
        2. Navigate to...
        3. Click on...
        4. See error
    id: steps-to-reproduce
    type: textarea
    validations:
      required: true

  - attributes:
      description: How frequently can you reproduce this issue?
      label: How often does this occur?
      options:
        - Select frequency
        - Always
        - Often
        - Sometimes
        - Rarely
        - First time
    id: frequency
    type: dropdown
    validations:
      required: true

  - attributes:
      description: Any error messages, screenshots, or additional context
      label: Additional Information (optional)
      placeholder: |
        Examples of helpful information:
        - Error messages or dialog boxes that appeared
        - Screenshots or screen recordings
        - Recent app updates (e.g., "Updated to v1.2.0 yesterday")
        - Network conditions (VPN, offline, etc.)
        - Workarounds you've discovered
        - Console logs or debug information
    id: additional-info
    type: textarea
    validations:
      required: false

  - attributes:
      description: Please confirm the following
      label: Acknowledgments
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
    id: terms
    type: checkboxes
description: Report a bug or issue with the Quests desktop application
labels: ["bug"]
name: 🐛 Bug Report
