blank_issues_enabled: false
contact_links:
  - about: Ask questions and get help from the community
    name: Discussions
    url: https://github.com/quests-org/quests/discussions
  - about: Check the documentation for usage instructions
    name: Documentation
    url: https://github.com/quests-org/quests#readme
